// pdfFieldMap.js
export const pdfFieldMapS2 = {
    vaccName: 'vACC Name',
    examineeName: 'Examinee Information',
    nameExaminer: 'Name Examiner',
    facilityTwr: 'Facility - ICAO_TWR',
    sessionDate: 'Sessión Date',
    startTime: 'Start Time',
    endTime: 'End Time',
    sessionPerformed: 'Session was performed',
    complexity: 'Complexity',
    workload: 'Workload',
    trafficLoad: 'Traffic Load',
    examineeResult: 'Examinee',
    examineeCid: 'Examinee CID',
    cidExaminer: 'CID Examiner',
    ratingExaminer2: 'Rating Examiner 2',
    examinerName1: 'Name Examiner Local 1',
    examinerCid1: 'CID Examiner  Local 1',
    examinerRating1: 'Rating Examiner 1 Local 1',
    examinerName2: 'Name Examiner Local 2',
    examinerCid2: 'CID Examiner  Local 2',
    examinerRating2: 'Rating Examiner 2 Local 2',
    //GENERAL
    correctConnectNetwork: 'Correctly Connects to the Network',
    understandsRole: 'Understans the Role and Responsability',
    demonstratesSoftware: 'Demonstrate correct use of the Software',
    professionalBehavior: 'Demonstrate professional behaviour',
    generalComments: 'General Comments',

    //ATC Competencies
    runwayConfig: 'Selects a suitable runway configuration and generates ATIS Issues appropriate clearance and departure instructions',
    clearanceInstructions: 'Issues appropriate clearance and departure instructions',
    groundClearances: 'Issues appropriate ground movement clearances',
    takeoffLanding: 'Issues appropriate Take-off/Landing clearances',
    missedApproaches: 'Correctly handles missed approaches',
    vfrTraffic: 'Manages VFR traffic correctly',
    trafficInfo: 'Provides traffic information when suitable and appropriate',
    situationalAwareness: 'Demonstrates situational awareness and frequency management',
    procedures: 'Knows and applies procedures and agreements correctly',
    atcComments: 'ATC Comments',

    //Communications
    phraseology: 'Demonstrates the use of appropriate phraseology',
    commPriority: 'Correctly manages communication priority',
    coordination: 'Performs the required coordination',
    handover: 'Correctly takes over and hands over the position',
    commComments: 'Communication Comments',

    finalReview: 'Final Review',
};

export const pdfFieldMapS3 = {
    vaccName: 'vACC Name',
    examineeName: 'Examinee Information',
    nameExaminer: 'Name Examiner',
    facilityTwr: 'Facility - ICAO_TWR',
    sessionDate: 'Sessión Date',
    startTime: 'Start Time',
    endTime: 'End Time',
    sessionPerformed: 'Session was performed',
    complexity: 'Complexity',
    workload: 'Workload',
    trafficLoad: 'Traffic Load',
    examineeResult: 'Examinee',
    examineeCid: 'Examinee CID',
    cidExaminer: 'CID Examiner',
    ratingExaminer2: 'Rating Examiner 2',
    examinerName1: 'Name Examiner Local 1',
    examinerCid1: 'CID Examiner  Local 1',
    examinerRating1: 'Rating Examiner 2 Local 1',
    examinerName2: 'Name Examiner Local 2',
    examinerCid2: 'CID Examiner  Local 2',
    examinerRating2: 'Rating Examiner 2 Local 2',
    //GENERAL
    understandsRole: 'Understands the role and responsibility',
    demonstratesSoftware: 'Demonstrates correct use of the software',
    professionalBehavior: 'Demonstrates professional behaviour and pleasant attitude',
    topdown: 'Correctly performs the top-down coverage',
    generalComments: 'General Comments',

    //ATC Competencies
    safetyBuffers: 'Handles the traffic safely, applying separation criteria and with adequate safety buffers',
    modeC: 'Correctly identifies aircraft, including verification of Mode C',
    SIDSTAR: 'Uses SIDs and STARs as required',
    inboundSpacing: 'Achieves inbound spacing as required',
    mixedIFR: "Manages VFR traffic mixed with IFR traffic and traffic entering/exiting the TMA",
    trafficInfo: 'Provides traffic information when suitable and appropriate',
    holding: 'Makes use of holding stacks when required and manages them appropriately',
    planOnTime: 'Makes a plan on time, is creative and flexible',
    trafficComplexity: 'Adapts workload to traffic complexity, is able to prioritize and keeps concentrated',
    situationalAwareness: 'Demonstrates situational awareness and frequency management',
    procedures: 'Knows and applies procedures and agreements correctly',
    atcComments: 'ATC Comments',

    //Communications
    approPhraseology: 'Demonstrates the use of appropriate phraseology',
    commPriority: 'Correctly manages communication priority',
    coordination: 'Performs the required coordination',
    handover: 'Correctly takes over and hands over the position',
    commComments: 'Communication Comments',
    finalReview: 'Final Review',

}


export const pdfFieldMapC1 = {
    vaccName: 'vACC Name',
    examineeName: 'Examinee Information',
    nameExaminer: 'Name Examiner',
    facilityTwr: 'Facility - ICAO_TWR',
    sessionDate: 'Sessión Date',
    startTime: 'Start Time',
    endTime: 'End Time',
    sessionPerformed: 'Session was performed',
    complexity: 'Complexity',
    workload: 'Workload',
    trafficLoad: 'Traffic Load',
    examineeResult: 'Examinee',
    examineeCid: 'Examinee CID',
    cidExaminer: 'CID Examiner',
    ratingExaminer2: 'Rating Examiner 2',
    examinerName1: 'Name Examiner Local 1',
    examinerCid1: 'CID Examiner  Local 1',
    examinerRating1: 'Rating Examiner 2 Local 1',
    examinerName2: 'Name Examiner Local 2',
    examinerCid2: 'CID Examiner  Local 2',
    examinerRating2: 'Rating Examiner 2 Local 2',
    //GENERAL
    understandsRole: 'Understands the role and responsibility',
    demonstratesSoftware: 'Demonstrates correct use of the software',
    professionalBehavior: 'Demonstrates professional behaviour and pleasant attitude',
    topdown: 'Correctly performs the top-down coverage',
    generalComments: 'General Comments',

    //ATC Competencies
    safetyBuffers: 'Handles the traffic safely, applying separation criteria and with adequate safety buffers',
    modeC: 'Correctly identifies aircraft, including verification of Mode C',
    SIDSTAR: 'Uses SIDs and STARs as required',
    inboundSpacing: 'Achieves inbound spacing as required',
    holding: 'Makes use of holding stacks when required and manages them appropriately',
    atcClass: 'Provides ATS services according to Airspace Class',
    anticipates: 'Anticipates conflicts and uses the require technique to solve them',
    planOnTime: 'Makes a plan on time, is creative and flexible',
    trafficComplexity: 'Adapts workload to traffic complexity, is able to prioritize and keeps concentrated',
    situationalAwareness: 'Demonstrates situational awareness and frequency management',
    procedures: 'Knows and applies procedures and agreements correctly',
    atcComments: 'ATC Comments',

    //Communications
    approPhraseology: 'Demonstrates the use of appropriate phraseology',
    commPriority: 'Correctly manages communication priority',
    coordination: 'Performs the required coordination',
    handover: 'Correctly takes over and hands over the position',
    commComments: 'Communication Comments',
    finalReview: 'Final Review',

}